import { type NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";

const SideNav = dynamic(() => import("@/components/ui/SideNav"), {
  loading: () => <p>Loading...</p>,
});
const NewTweetForm = dynamic(() => import("@/components/tweets/NewTweetForm"), {
  loading: () => <p>Loading...</p>,
});
const RecentTweets = dynamic(() => import("@/components/tweets/RecentTweets"), {
  loading: () => <p>Loading...</p>,
});
const Home: NextPage = () => {
  return (
    <section className="container mx-auto flex items-start sm:pr-4">
      <Head>
        <title>Tweet Clone T3 APP</title>
        <meta
          name="description"
          content="Twitter Clone by Santipac generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideNav />
      <main className="min-h-screen flex-grow border-x">
        <header className="sticky top-0 z-10 border-b bg-white pt-2">
          <h1 className="mb-2 px-4 text-lg font-bold">Home</h1>
        </header>
        <NewTweetForm />
        <RecentTweets />
      </main>
    </section>
  );
};

export default Home;
